In [1]:
import numpy as np

In [2]:
mylist=[1,2,3]
type(mylist)

list

In [3]:
myarray = np.array(mylist)
type(myarray)

numpy.ndarray

In [4]:
mymatrix=[[1,2,3],[4,5,6],[7,8,9]]
type(mymatrix)

list

In [5]:
my_matrix = np.array(mymatrix)
type(my_matrix)

numpy.ndarray

In [6]:
mymatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
one_to_nine = np.arange(0,10)
type(one_to_nine)

numpy.ndarray

In [9]:
one_to_nine

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
evens_to_nine = np.arange(0,10,2)
evens_to_nine

array([0, 2, 4, 6, 8])

In [11]:
five_zeros=np.zeros(5)
five_zeros

array([0., 0., 0., 0., 0.])

In [12]:
ten_zeros = np.zeros((2,5))
ten_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
begining = 0
ending = 20
how_many = 3
np.linspace(begining, ending, how_many) # produce 3 evenly distributed numbers between 0 and 20

array([ 0., 10., 20.])

In [15]:
 #Identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## distributions

In [16]:
# uniform distribution
np.random.rand(5,2) #five rows, two columns

array([[0.63622258, 0.96777801],
       [0.23452134, 0.54961159],
       [0.08961404, 0.53133889],
       [0.48140474, 0.01066359],
       [0.32277319, 0.22779924]])

In [17]:
#Normal distribution with mean = 0 and stdev = 1
np.random.randn(10)

array([ 0.67005751,  0.07944442, -1.31086999, -0.05698544,  0.01422682,
       -0.03349547,  2.09597402, -0.79221982, -0.06407104,  0.05597218])

In [18]:
np.random.randn(2,5)

array([[-1.25524145, -1.00347657, -0.48129195, -1.96453442, -0.88809659],
       [-1.31273046, -0.22082197,  0.57413444, -0.38037161,  1.48599185]])

In [19]:
#getting integers
np.random.randint(0,101, 5)

array([41, 48, 97, 30, 80], dtype=int32)

In [20]:
np.random.randint(0,101, (3,5))

array([[10, 76, 60, 19, 34],
       [97, 92,  5, 21, 81],
       [86, 94,  6, 24, 63]], dtype=int32)

In [21]:
# You may get repeatable set of random numbers by using a seed
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [22]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
#change the dimensionality
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
 ranarr = np.random.randint(0,101,10)

In [25]:
ranarr.max()

np.int32(99)

In [26]:
ranarr.min()

np.int32(2)

In [27]:
#find out where the maximum is
ranarr.argmax()

np.int64(5)

In [28]:
ranarr[5]

np.int32(99)

In [29]:
ranarr.argmin()

np.int64(7)

In [30]:
ranarr[7]

np.int32(2)

In [31]:
type(arr)

numpy.ndarray

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

 More documentation in numpy.org