 More documentation in numpy.org

# Numpy indexing

In [3]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
arr[8]

np.int64(8)

In [3]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [4]:
arr[:5]

array([0, 1, 2, 3, 4])

In [5]:
arr[8:11]

array([ 8,  9, 10])

In [6]:
arr[8:]

array([ 8,  9, 10])

### Broadcasting

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr[0:5] = np.arange(0,5)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [11]:
slice_of_arr[:] =99
slice_of_arr

array([99, 99, 99, 99, 99])

In [12]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [13]:
arr_copy = slice_of_arr = arr[0:5].copy()
arr_copy

array([99, 99, 99, 99, 99])

In [14]:
arr_copy[:4]=np.arange(0,4)
arr_copy

array([ 0,  1,  2,  3, 99])

In [15]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

### 2-d 

In [16]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
arr_2d.shape

(3, 3)

In [18]:
arr_2d[2]

array([35, 40, 45])

In [19]:
arr_2d[1][1]

np.int64(25)

In [20]:
arr_2d[1,1]

np.int64(25)

In [21]:
arr_2d[0,2]

np.int64(15)

In [22]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [23]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

### condition selection

In [24]:
arr > 9

array([ True,  True,  True,  True,  True, False, False, False, False,
       False,  True])

In [25]:
bool_arr = arr>9

In [26]:
arr[bool_arr]

array([99, 99, 99, 99, 99, 10])

In [27]:
arr[arr>9]

array([99, 99, 99, 99, 99, 10])

In [28]:
len(arr[arr>9])

6

## Operations

In [4]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
arr -2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [32]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
# warning instead of exception
arr / arr

C:\Users\mvgarcia\AppData\Local\Temp\ipykernel_5812\3036351373.py:2: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [6]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [7]:
np.log(arr)

C:\Users\mvgarcia\AppData\Local\Temp\ipykernel_5812\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [8]:
arr.sum()

np.int64(45)

In [9]:
arr.mean()

np.float64(4.5)

In [10]:
arr.max()

np.int64(9)

In [11]:

arr.min()

np.int64(0)

In [12]:
arr.var()

np.float64(8.25)

In [13]:
arr.std()

np.float64(2.8722813232690143)

In [15]:
arr2d= np.arange(0,25).reshape(5,5)

In [16]:
arr2d.sum()

np.int64(300)

In [17]:
#sum of each column
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [19]:
#sum of each row
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [22]:
arr2d.sum(axis=0).sum()

np.int64(300)

In [23]:
arr2d.sum(axis=1).sum()

np.int64(300)